export const UNIVERSITATI = [
  'Universitatea Politehnica București (UPB)',
  'Academia de Studii Economice din București (ASE)',
  'Universitatea din București (UniBuc)',
  'Universitatea Babeș-Bolyai Cluj-Napoca (UBB)',
  'Universitatea Tehnică din Cluj-Napoca (UTCN)',
  'Universitatea de Vest din Timișoara (UVT)',
  'Universitatea Politehnica Timișoara (UPT)',
  'Universitatea Alexandru Ioan Cuza din Iași (UAIC)',
  'Universitatea Tehnică „Gheorghe Asachi" din Iași (TUIASI)',
  'Universitatea Transilvania din Brașov',
  'Universitatea din Craiova',
  'Universitatea Ovidius din Constanța',
  'Universitatea Ștefan cel Mare din Suceava',
  'Universitatea din Pitești',
  'Universitatea Dunărea de Jos din Galați',
  'Universitatea „Lucian Blaga" din Sibiu',
  'Universitatea de Medicină și Farmacie „Carol Davila" București',
  'Universitatea de Medicină și Farmacie Cluj-Napoca',
  'Universitatea de Medicină și Farmacie din Iași',
  'Universitatea de Arhitectură și Urbanism „Ion Mincu" București',
  'Academia Națională de Arte București',
  'Universitatea Națională de Arte din București',
  'Universitatea Națională de Muzică București',
  'Universitatea din Petroșani',
  'Universitatea „Valahia" din Târgoviște',
  'Universitatea „Aurel Vlaicu" din Arad',
  'Universitatea „Eftimie Murgu" din Reșița',
  'Universitatea „1 Decembrie 1918" din Alba Iulia',
  'Alta universitate',
]
